name: sunrise_sunset_calc
description: Calculates sunrise and sunset time given latitude, longitude, timezone offset and date.
version: 2.2.0
homepage: https://github.com/aquilax/sunrise-sunset-calc

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  async: ^2.8.1
  vector_math: ^2.1.0

dev_dependencies:
  test: ^1.16.8
  benchmark_harness: any
  lints: ^1.0.1
