name: sunrise_sunset_calc
description: Calculates sunrise and sunset time given coordinates
version: 1.0.0
homepage: https://github.com/aquilax/sunrise-sunset-calc
author: aquilax <aquilax@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
