name: sunrise_sunset_calc
description: Calculates sunrise and sunset time given latitude, longitude, timezone offset and date.
version: 2.0.0
homepage: https://github.com/aquilax/sunrise-sunset-calc

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
  benchmark_harness: any